"""modelado jpastor

Revision ID: 258177e59a89
Revises: 943e8132eb25
Create Date: 2024-11-30 17:02:04.335764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258177e59a89'
down_revision = '943e8132eb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.String(length=100), nullable=True),
    sa.Column('hora', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stand', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('days_open', sa.String(length=50), nullable=True),
    sa.Column('schedule', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('photo_menu_1', sa.String(length=255), nullable=True),
    sa.Column('photo_menu_2', sa.String(length=255), nullable=True),
    sa.Column('photo_menu_3', sa.String(length=255), nullable=True),
    sa.Column('photo_primary', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotions')
    op.drop_table('stores')
    op.drop_table('events')
    # ### end Alembic commands ###
