"""modelado jpastor02

Revision ID: 5d2c463fbaf5
Revises: 258177e59a89
Create Date: 2024-11-30 17:42:09.438810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2c463fbaf5'
down_revision = '258177e59a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
